require('baibs.plugins-setup') -- Should be at the top
require('baibs.core.colorscheme')
require('baibs.core.options')
require('baibs.core.keymaps')
require('baibs.plugins.comment')
require('baibs.plugins.nvim-tree')
require('baibs.plugins.lualine')
require('baibs.plugins.telescope')
require('baibs.plugins.nvim-cmp')
require('baibs.plugins.lsp.mason')
require('baibs.plugins.lsp.lspsaga')
require('baibs.plugins.lsp.lspconfig')
require('baibs.plugins.autoclose')
require('baibs.plugins.42header')
